apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.deployment }}
  namespace: cert-manager
spec:
  acme:
    server: https://api.buypass.com/acme/directory
    email: "lbnvd13@yandex.ru"
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.deployment }}
    solvers:
    - http01:
        ingress:
          class: nginx
