apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-{{ .Values.deployment }}"
spec:
  {{- if eq .Values.deployment "prod" }}
  tls:
    - hosts:
      - "ui.{{ .Values.deployment }}.158.160.100.96.nip.io"
      secretName: letsencrypt-{{ .Values.deployment }}
  {{- end}}
  rules:
  - host: "ui.{{ .Values.deployment }}.158.160.100.96.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ui
            port:
              number: 8000
